import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';


export default function Home() {
  const [batteryCharging, setBatteryCharging] = useState(true)
  const [batteryLevel, setBatteryLevel] = useState(0)
  useEffect(() => {
 navigator.getBattery().then((battery) => {
  function updateAllBatteryInfo() {
    updateChargeInfo();
    updateLevelInfo();
    updateChargingInfo();
    updateDischargingInfo();
  }
  updateAllBatteryInfo();

  battery.addEventListener("chargingchange", () => {
    updateChargeInfo();
  });
  function updateChargeInfo() {
    console.log(`Battery charging? ${battery.charging ? "Yes" : "No"}`);
    setBatteryCharging(battery.charging);
  }

  battery.addEventListener("levelchange", () => {
    updateLevelInfo();
  });
  function updateLevelInfo() {
     console.log(`Battery level: ${battery.level * 100}%`);
    setBatteryLevel(battery.level * 100);
  }

  battery.addEventListener("chargingtimechange", () => {
    updateChargingInfo();
  });
  function updateChargingInfo() {
    console.log(`Battery charging time: ${battery.chargingTime} seconds`);
  }

  battery.addEventListener("dischargingtimechange", () => {
    updateDischargingInfo();
  });
  function updateDischargingInfo() {
    console.log(`Battery discharging time: ${battery.dischargingTime} seconds`);
  }
});


  },[setBatteryLevel])
 

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#141414] w-full h-screen text-green-500 flex flex-col justify-center items-center'>
        <div>
          Battery Percentage
        </div>
        <div className='liquid'>
          {batteryLevel}
        </div>
      </main>
    </>
  )
}
